services:
  server:
    build:
      context: .
    image: thanhtrung23/java-spring-boot
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/thanhtrung23
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=thanhtrung23
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      # Lệnh kiểm tra xem MySQL đã sẵn sàng nhận kết nối chưa
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: